
name: NodeCICD

on:
  push:
    branches: [ "main" ]


jobs:
  frontend-build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install and Build React App
      working-directory: frontend
      run: |
        npm ci
        npm run build
    - name: Docker Build and Push (Frontend)
      run: |
        docker build -t 17rj/three-tier-game-frontend frontend/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push 17rj/three-tier-game-frontend:latest
        
  backend-build:
    needs: frontend-build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Docker Build and Push (Backend)
      run: |
        docker build -t 17rj/three-tier-game-backend backend/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push 17rj/three-tier-game-backend:latest
        
  deploy-k8s-aks:
    needs: backend-build
    runs-on: self-hosted
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group gitlab --name dev --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/

    
  
